Repository TeamNewPipe/NewPlayer, pull requests merged in 2025-02, with the labels that each got.

#16 StreamTrack: implement sorting as Comparator
  new-player/src/main/java/net/newpipe/newplayer/data/StreamTrack.kt
  new-player/src/main/java/net/newpipe/newplayer/logic/TrackUtils.kt
Labels: enhancement, code quality

#11 Add Tests for NewPlayer
  gradle/libs.versions.toml
  new-player/build.gradle.kts
  new-player/src/main/java/net/newpipe/newplayer/repository/PrefetchingRepository.kt
  new-player/src/main/java/net/newpipe/newplayer/uiModel/NewPlayerViewModelImpl.kt
  new-player/src/test/java/net/newpipe/newplayer/NewPlayerImpltest.kt
  new-player/src/test/java/net/newpipe/newplayer/repository/CachingRepositoryTest.kt
  new-player/src/test/java/net/newpipe/newplayer/repository/MockMediaRepository.kt
  new-player/src/test/java/net/newpipe/newplayer/repository/PrefetchingRepositoryTest.kt
  new-player/src/test/java/net/newpipe/newplayer/uiModel/NewPlayerViewModelImpltest.kt
Labels: tests, code quality

#18 Introduce seek chapter title preview
  new-player/src/main/java/net/newpipe/newplayer/ui/common/ThumbPreview.kt
  new-player/src/main/java/net/newpipe/newplayer/uiModel/NewPlayerUIState.kt
  new-player/src/main/java/net/newpipe/newplayer/uiModel/NewPlayerViewModelImpl.kt
Labels: enhancement
